name: Gradle checks

env:
  cache-name: android-gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble with Gradle
        run: ./gradlew :app:preDebugBuild :app:preReleaseBuild :gears:preDebugBuild :gears:preReleaseBuild --no-daemon

  unit-tests:
    needs: setup

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble dependencies
        run: ./gradlew trigonometry:assemble

      - name: Publish dependencies to local maven
        run: ./gradlew :trigonometry:publishToMavenLocal

      - name: Assemble
        run: ./gradlew gears:assemble jigsaw:assemble

      - name: Publish to local maven
        run: ./gradlew :gears:publishToMavenLocal :jigsaw:publishToMavenLocal

      - name: Run unit tests
        run: ./gradlew test

  lint:
    needs: setup

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble dependencies
        run: ./gradlew trigonometry:assemble

      - name: Publish dependencies to local maven
        run: ./gradlew :trigonometry:publishToMavenLocal

      - name: Assemble
        run: ./gradlew gears:assemble jigsaw:assemble

      - name: Publish to local maven
        run: ./gradlew :gears:publishToMavenLocal :jigsaw:publishToMavenLocal

      - name: Assemble app
        run: ./gradlew :app:assemble

      - name: Run lint
        run: ./gradlew lint --no-daemon
